### ISSUE TITLE
Missing aJSON.h

### ISSUE THREAD

**Issue by RGB-123** [pixelmatix/aurora#10]
Louis, it looks like the #include "aJSON.h" is missing from this repo.  Can you please push this update?

**Comment by pup05** [comment]
I see that include in Aurora.ino in the master branch: https://github.com/pixelmatix/aurora/blob/master/Aurora.ino#L51

**Comment by RGB-123** [comment]
Right, the include is in there, but the actual file is not in the repo and hence I can't compile aurora.

**Comment by pup05** [comment]
Yeah, you have to download it separately, just like all the other libraries (SmartMatrix, FastLED, etc).  It wasn't originally mentioned in the libraries list until recently.  See the Compiling page in the wiki for more info: https://github.com/pixelmatix/aurora/wiki/Compiling

**Comment by RGB-123** [comment]
Got it.  I was looking at the readme.md and should've gone to the wiki.  Good work on the wiki BTW!

**Comment by pup05** [comment]
Cool, sorry for the trouble, that was something I missed and another user fixed.  :)  Thanks!

**Comment by kigster** [comment]
@RGB-123 actually aJSON library is included in README also.
