### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tarbear123** [pixelmatix/aurora#40]
what do these mean?
```
void listAnimations() {
  animations.listFiles();
}

void reloadAnimations() {
  animations.setup((char *)"/gifs/");
}

bool setAnimation(String name) {
  if (animations.setAnimation(name)) {
    menu.currentIndex = 2;
    menu.visible = false;
    return true;
  }
  return false;
}

bool setAnimation(int index) {
  if (animations.setAnimation(index)) {
    menu.currentIndex = 2;
    menu.visible = false;
    return true;
  }

  return false;
}
```
and if the sd finds gifs, will it display on a led matrx?

**Comment by embedded-creations** [comment]
It's well written code.  If you're confused with something after trying to interpret it, you can ask a specific question, but I'm not going to interpret a big block of code for you.

> and if the sd finds gifs, will it display on a led matrx?

Yes.  Try to get the AnimatedGifs sketch working first, Aurora is more complicated.

I'm going to close this issue as it's not an issue.  You're welcome to post questions to our community: community.pixelmatix.com
